import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { SearchResult } from '../types';
import { ExternalLink, BookOpen, Globe, Printer, Copy, Check, Share2 } from 'lucide-react';

interface ResultsRendererProps {
  result: SearchResult;
  origin: string;
  destination: string;
}

const ResultsRenderer: React.FC<ResultsRendererProps> = ({ result, origin, destination }) => {
  const [copied, setCopied] = useState(false);
  
  const handlePrint = () => {
    window.print();
  };

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(result.markdown);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy text', err);
    }
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: `Driving Guide: ${origin} to ${destination}`,
          text: `Check out this driving guide for traveling from ${origin} to ${destination}.`,
          url: window.location.href,
        });
      } catch (error) {
        console.log('Error sharing:', error);
      }
    } else {
      // Fallback to copy if share API not supported
      handleCopy();
    }
  };

  return (
    <div id="printable-result" className="animate-fade-in-up relative">
      
      {/* Header for Print/PDF only */}
      <div className="hidden print:block mb-8 text-center border-b pb-4">
        <h1 className="text-2xl font-bold text-slate-900">Driving Requirement Report</h1>
        <p className="text-slate-500">Generated by GlobalDrive AI | {origin} → {destination}</p>
        <p className="text-xs text-slate-400 mt-1">{new Date().toLocaleDateString()}</p>
      </div>

      {/* Action Bar */}
      <div className="flex flex-wrap justify-end mb-4 gap-2 no-print">
        <button 
          onClick={handleShare}
          className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-indigo-600 bg-slate-50 hover:bg-white border border-slate-200 px-3 py-1.5 rounded-lg transition-all"
          title="Share Guide"
        >
          <Share2 size={16} />
          <span className="hidden sm:inline">Share</span>
        </button>

        <button 
          onClick={handleCopy}
          className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-indigo-600 bg-slate-50 hover:bg-white border border-slate-200 px-3 py-1.5 rounded-lg transition-all"
          title="Copy Report to Clipboard"
        >
          {copied ? <Check size={16} className="text-green-500" /> : <Copy size={16} />}
          <span className="hidden sm:inline">{copied ? 'Copied!' : 'Copy'}</span>
        </button>

        <button 
          onClick={handlePrint}
          className="flex items-center gap-2 text-sm font-medium text-slate-600 hover:text-indigo-600 bg-slate-50 hover:bg-white border border-slate-200 px-3 py-1.5 rounded-lg transition-all"
          title="Print or Save as PDF"
        >
          <Printer size={16} />
          <span className="hidden sm:inline">Print / PDF</span>
        </button>
      </div>

      {/* Main Content */}
      <div className="prose prose-slate max-w-none prose-headings:text-slate-800 prose-p:text-slate-600 prose-li:text-slate-600 prose-strong:text-indigo-700 prose-table:border-collapse prose-td:border prose-td:border-slate-200 prose-td:p-2 prose-th:bg-slate-50 prose-th:p-2 prose-th:border prose-th:border-slate-200">
        <ReactMarkdown
            components={{
                h1: ({node, ...props}) => <h1 className="text-2xl font-bold text-slate-800 mb-4 border-b pb-2" {...props} />,
                h2: ({node, ...props}) => <h2 className="text-xl font-semibold text-slate-800 mt-8 mb-3 flex items-center gap-2" {...props} />,
                li: ({node, ...props}) => <li className="my-1" {...props} />,
                ul: ({node, ...props}) => <ul className="list-disc list-outside ml-5 mb-4" {...props} />,
                table: ({node, ...props}) => <div className="overflow-x-auto my-6 rounded-lg border border-slate-200"><table className="w-full text-sm text-left" {...props} /></div>,
                blockquote: ({node, ...props}) => (
                  <blockquote className="border-l-4 border-indigo-400 bg-indigo-50 pl-4 py-2 italic text-slate-700 rounded-r-lg my-4" {...props} />
                )
            }}
        >
            {result.markdown}
        </ReactMarkdown>
      </div>

      {/* Sources Section */}
      {result.sources.length > 0 && (
        <div className="mt-8 border-t border-slate-200 pt-6">
          <h3 className="text-sm font-semibold text-slate-500 uppercase tracking-wider mb-3 flex items-center gap-2">
            <Globe size={16} />
            Verified Sources
          </h3>
          <div className="grid gap-2 sm:grid-cols-2">
            {result.sources.map((source, index) => (
              <a
                key={index}
                href={source.web?.uri}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-start gap-3 p-3 rounded-lg bg-white border border-slate-200 hover:border-indigo-300 hover:shadow-sm transition-all group no-print-decoration"
              >
                <div className="mt-1 text-indigo-500 group-hover:text-indigo-600 shrink-0">
                  <ExternalLink size={16} />
                </div>
                <div className="overflow-hidden">
                  <p className="text-sm font-medium text-slate-700 truncate group-hover:text-indigo-700 transition-colors">
                    {source.web?.title || 'Official Source'}
                  </p>
                  <p className="text-xs text-slate-400 truncate">
                    {source.web?.uri}
                  </p>
                </div>
              </a>
            ))}
          </div>
        </div>
      )}
      
      {result.sources.length === 0 && (
        <div className="mt-8 p-4 bg-yellow-50 text-yellow-800 rounded-lg text-sm flex items-center gap-2">
            <BookOpen size={16} />
            <span>Note: No direct web citations were returned, but the AI uses general knowledge. Always verify with a local embassy.</span>
        </div>
      )}
      
      <div className="mt-8 pt-4 border-t border-slate-100 text-center print:block hidden">
         <p className="text-xs text-slate-400">Disclaimer: This document is for informational purposes only. Official regulations take precedence.</p>
      </div>
    </div>
  );
};

export default ResultsRenderer;